apiVersion: v1
data:
  global-allowed-response-headers: "X-Different-Name,X-Request-Start,X-Using-Nginx-Controller"
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
